---
# Ansible inventory file example
all:
  children:
    windows:
      vars:
        ansible_connection: psrp
        ansible_psrp_protocol: https
        ansible_psrp_auth: kerberos
        ansible_psrp_user: username@DTROTSKII.LOCAL
        ansible_psrp_negotiate_delegate: true
        ansible_psrp_cert_validation: ignore
      children:
        ad:
          hosts:
            hostname.dtrotskii.local:
